[general]
access_password = "cleaneats2025"
github_token = "ghp_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"
github_repo = "LukeCreativeInd/cleaneatscostings"
github_branch = "main"  # or 'master' or whatever branch you want
